### PR TITLE
FYSA: my edits.

### PR DESCRIPTION
**Pull request by arokem**

### CODE REVIEW

**Comment by choldgraf** [comment]
any high-level thoughts etc?

**Comment by arokem** [comment]
A couple of high-level thoughts, related to the introduction:

- I thought that some concepts might need to be introduced earlier. In particular, Docker plays a really important role in all this, so it might be worth mentioning up-front in the introduction. This is actually a more compelling use-case (IMHO) than many other use-cases that researchers use Docker for (e.g., as a tool to reproduce specific analysis). 

- Relatedly, the introduction feels a bit short at the moment, and we might want to make a bit more of a case for why the paper fits into the particular context of this conference.

**Comment by choldgraf** [comment]
These are good points - re: the docker stuff, I wasn't sure what kind of audience we'd have (e.g., if everybody would already be seasoned docker veteran).

**Comment by arokem** [comment]
Even for the seasoned readers (maybe even more for them!) we want to let
them know that Docker is going to be a key player in the drama about to
unfold (would even consider adding that into the title!)

**Comment by choldgraf** [comment]
Feel free to edit the title, I like your idea and think it's more specific to the topic

**Pull request merged**
